### PR TITLE
Put fingerprint before extension, instead of as querystring

### PR DESCRIPTION
**Pull request by nberger**
Plays better with proxies, etc

### CODE REVIEW

**Comment by nberger** [comment]
I just realized that the files are not moved to the fingerprinted name... I can add that, but that's a bigger change, so first I'd like to know if you are interested on this change @ddeaguiar

**Comment by nberger** [comment]
Added new commits to take care of actually copying the file with the new name so it's found in the file system. This is working to me.

**Comment by nberger** [comment]
By the way, thanks to @jolisper & @allentiak for their help on this feature!

**Comment by ddeaguiar** [comment]
Thanks for this. I'm wondering if we should support both strategies. @christianromney thoughts?

**Comment by nberger** [comment]
As far as I remember, there were some missing pieces here, and I'm not looking to use it in the near future, so I'm closing this PR

**Pull request closed without merging**
